const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
const repo=require('node:path').resolve(__dirname,'../..'),wait=ms=>new Promise(r=>setTimeout(r,ms));
const dom=new JSDOM('<!doctype html><head></head><body></body>',{runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
for(const p of ['tools/libs/marked.min.js','tools/libs/purify.min.js','tools/libs/highlight.min.js','js/shared/render-runtime.js','js/shared/markdown-options.js','js/shared/html-import-structures.js','js/shared/html-to-markdown.js','js/shared/html-blocks.js','js/shared/code-blocks.js','js/pdf-maker/math.js','js/pdf-maker/document-state.js','js/markdown-editor/preview-renderer.js'])w.eval(fs.readFileSync(repo+'/'+p,'utf8'));
w.eval(fs.readFileSync(require.resolve('katex/dist/katex.min.js'),'utf8'));w.marked.setOptions({renderer:w.SharedCodeBlocks.configureRenderer(new w.marked.Renderer())});
const convert=(html,mode='strict',auto=false)=>{const model=w.HtmlToMarkdown.prepare(html),choices=new Map();if(auto)w.HtmlToMarkdown.autoResolve(model,mode,choices);return w.HtmlToMarkdown.convert(model,mode,choices)};
(async()=>{
 let r=convert('<table><tr><th rowspan="2">Group</th><th>Value</th></tr><tr><td>20</td></tr></table>','strict',true);assert.equal(r.unresolved,0);assert(r.markdown.includes('|  | 20 |'));
 r=convert('<table><tbody><tr><td rowspan="0">A</td><td>B</td></tr><tr><td>C</td></tr></tbody><tbody><tr><td>D</td><td>E</td></tr></tbody></table>','strict',true);assert(r.markdown.includes('|  | C |'));assert(r.markdown.includes('| D | E |'));
 for(const html of ['<ol start="3" reversed><li>A</li><li>B</li><li>C</li></ol>','<ol><li>A</li><li value="9">B</li></ol>']){assert.equal(convert(html).unresolved,1);r=convert(html,'strict',true);assert.equal(r.unresolved,0);assert(!w.marked.parse(r.markdown).includes('<ol'));assert(convert(html,'html').markdown.includes('junny-html'));}
 assert(convert('<ol start="3" reversed><li>A</li><li>B</li><li>C</li></ol>','strict',true).markdown.includes('2\\. B'));assert(convert('<ol><li>A</li><li value="9">B</li></ol>','strict',true).markdown.includes('9\\. B'));
 assert(convert('<ol reversed><li>A</li><li>B</li></ol>','strict',true).markdown.startsWith('2\\. A'));
 r=convert('<math><mphantom><mi>x</mi></mphantom><mo>+</mo><mi>y</mi></math>');assert(r.markdown.includes('\\phantom{x}'));r=convert('<math><mtext>a{b} % # _ &amp;</mtext></math>');assert(r.markdown.includes('\\text{a\\{b\\} \\% \\# \\_ \\&}'));const math=w.document.createElement('div');math.innerHTML=w.PdfMath.parse(r.markdown);w.PdfMath.render(math);assert(!math.querySelector('.katex-error'));assert(math.querySelector('annotation').textContent.includes('\\{b\\}'));
 assert.equal(convert('<math><menclose><mi>x</mi></menclose></math>').unresolved,1);
 assert.throws(()=>w.HtmlToMarkdown.prepare('<div>'.repeat(300)+'x'+'</div>'.repeat(300)),/중첩/);
 // Prefix/suffix retain DOM identities and reference definitions invalidate all affected links.
 const host=w.document.createElement('div');w.document.body.append(host);const renderer=w.MdPreviewRenderer.create(host);
 renderer.update('# First\n\nKeep [ref][r]\n\n## Last\n\n[r]: https://one.test\n');const first=host.querySelector('h1'),last=host.querySelector('h2');assert.equal(host.querySelector('a').href,'https://one.test/');
 renderer.update('# First\n\nChanged\n\nKeep [ref][r]\n\n## Last\n\n[r]: https://one.test\n');assert.equal(host.querySelector('h1'),first);assert.equal(host.querySelector('h2'),last);assert.deepEqual([...host.children].map(n=>n.tagName),['H1','P','P','H2']);
 renderer.update('# First\n\nKeep [ref][r]\n\n## Last\n\n[r]: https://two.test\n');assert.equal(host.querySelector('a').href,'https://two.test/');
 renderer.update('Value $x_i$ and [ref][r]\n\n[r]: https://three.test\n');assert.equal(host.querySelector('a').href,'https://three.test/');w.PdfMath.render(host);assert(host.querySelector('.katex'));
 renderer.update('<div class="container">\n\n## Inner\n\nBody\n\n</div>\n\n## Outside');assert.equal(host.querySelector('.container h2').textContent,'Inner');assert.equal(host.children.length,2);assert(!host.querySelector('[data-md-source-token]'));const outside=renderer.update('<div class="container">\n\n## Inner\n\nBody\n\n</div>\n\n## Outside').blocks[1];assert(outside.line>5);
 // Identical CSS is shared; unchanged blocks perform no new DOMParser work.
 const blocks=w.document.createElement('div');w.document.body.append(blocks);blocks.innerHTML=Array.from({length:100},(_,i)=>w.SharedHtmlBlocks.renderFence('<style>td{color:blue}</style><table><tr><td>'+i+'</td></tr></table>')).join('');let parses=0;const parse=w.DOMParser.prototype.parseFromString;w.DOMParser.prototype.parseFromString=function(...args){parses++;return parse.apply(this,args)};w.SharedHtmlBlocks.hydrate(blocks);const coldParses=parses;assert(coldParses>=100);assert.equal(w.document.querySelectorAll('style[data-html-block-style]').length,1);w.SharedHtmlBlocks.hydrate(blocks);assert.equal(parses,coldParses);w.SharedHtmlBlocks.update(blocks.firstElementChild,'<style>td{color:blue}</style><table><tr><td>Updated</td></tr></table>');assert.equal(blocks.firstElementChild.textContent,'Updated');assert.equal(w.document.querySelectorAll('style[data-html-block-style]').length,1);w.DOMParser.prototype.parseFromString=parse;
 const cache=w.EditorRuntime.cache({entries:2,bytes:20});cache.set('a','1',5);cache.set('b','2',5);cache.get('a');cache.set('c','3',5);assert.equal(cache.get('b'),undefined);cache.set('oversize','x',100);assert(cache.bytes<=20);
 let calls=0;const job=w.EditorRuntime.job(()=>calls++,20);for(let i=0;i<5;i++)job.schedule();await wait(35);assert.equal(calls,1);job.schedule();job.cancel();await wait(35);assert.equal(calls,1);job.schedule();job.flush();assert.equal(calls,2);await wait(35);assert.equal(calls,2);
 // Math macro definitions must still affect retained nodes and cached formulas.
 host.innerHTML=w.PdfMath.parse('$\\gdef\\foo{a}$ $\\foo$');w.PdfMath.render(host);const formulas=host.querySelectorAll('.pdf-math');assert.equal(formulas[1].querySelector('.mord').textContent,'a');formulas[0].dataset.mathSource='\\gdef\\foo{b}';w.PdfMath.render(host);assert.equal(formulas[1].querySelector('.mord').textContent,'b');
 host.innerHTML=w.PdfMath.parse('$\\xdef\\foo{c}$ $\\foo$');w.PdfMath.render(host);w.PdfMath.render(host);assert.equal(host.querySelectorAll('.pdf-math')[1].querySelector('.mord').textContent,'c');
 const source=w.document.createElement('div');w.document.body.append(source);source.innerHTML='<p data-element-id="one">Old</p>';const state=w.PdfDocumentState.create(source),idx=w.EditorRuntime.index(source,'data-element-id');let serializes=0;const serialize=()=>{serializes++;return source.innerHTML};assert.equal(state.html(serialize),state.html(serialize));assert.equal(serializes,1);source.firstChild.textContent='New';assert(state.html(serialize).includes('New'));assert.equal(serializes,2);const old=idx.get('one');source.innerHTML='<p data-element-id="one">Restored</p>';assert.notEqual(idx.get('one'),old);const history=Array.from({length:30},(_,i)=>({html:'x'.repeat(100),settings:{i},title:'t',importedStyles:{}}));state.trim(history,1000);assert(history.length<30 && history.length>0);
 dom.window.close();console.log('PASS: merged cell coordinates, literal list numbers/HTML fallback, MathML semantics, complexity guards, DOM identity/reference links, HTML/CSS caches, bounded cache/jobs, macro invalidation and source/history indexes.');
 const markdown=require('./markdown-fixture.cjs');const a=await markdown('# Existing');const {w:v,$,cm}=a;v.HTMLDialogElement.prototype.showModal=function(){this.open=true};v.HTMLDialogElement.prototype.close=function(){this.open=false};$('htmlImportBtn').click();$('htmlImportSource').value='<h1>First</h1><p>Body</p>';$('htmlImportAnalyze').click();let renders=0,checks=0;const parseMath=v.PdfMath.parse,validate=v.HtmlToMarkdown.validate;v.PdfMath.parse=(...args)=>{renders++;return parseMath(...args)};v.HtmlToMarkdown.validate=(...args)=>{checks++;return validate(...args)};
 for(let i=0;i<5;i++){$('htmlImportOutput').value+='x';$('htmlImportOutput').dispatchEvent(new v.Event('input',{bubbles:true}));}assert($('htmlImportApply').disabled);await wait(220);assert.equal(renders,1);assert.equal(checks,1);assert(!$('htmlImportApply').disabled);
 // Simulate a loaded srcdoc, since jsdom itself does not load srcdoc resources.
 const frame=$('htmlImportResultPreview'),doc=frame.contentDocument;doc.body.setAttribute('data-import-preview','true');const srcdoc=frame.srcdoc;$('htmlImportOutput').value='# First\n\nKeep\n\nLast';$('htmlImportOutput').dispatchEvent(new v.Event('input',{bubbles:true}));await wait(220);const node=doc.body.querySelector('h1');$('htmlImportOutput').value+='. Edit';$('htmlImportOutput').dispatchEvent(new v.Event('input',{bubbles:true}));await wait(220);assert.equal(doc.body.querySelector('h1'),node);assert.equal(frame.srcdoc,srcdoc);assert(doc.body.textContent.includes('Last. Edit'));
 $('htmlImportOutput').value+='<script>bad</script>';$('htmlImportOutput').dispatchEvent(new v.Event('input',{bubbles:true}));$('htmlImportCancel').click();const before=renders;await wait(220);assert.equal(renders,before);assert.equal(cm.getValue(),'# Existing');$('htmlImportBtn').click();$('htmlImportSource').value='<div>'.repeat(300)+'x'+'</div>'.repeat(300);$('htmlImportAnalyze').click();assert($('htmlImportApply').disabled);assert($('htmlImportStatus').textContent.includes('중첩'));assert.equal(cm.getValue(),'# Existing');a.dom.window.close();console.log('PASS: modal burst coalescing, pending validation gate, live iframe DOM/scroll document retention, close cancellation and invalid-input preservation.');
 const app=require('./app-fixture.cjs');const p=await app(),d=p.$;await p.load('<h1>Top</h1>'+Array.from({length:200},(_,i)=>'<p>Paragraph '+i+' '+('text '.repeat(30))+'</p>').join(''));const pages=p.pages();assert(pages.length>5);const block=d('sourceContent').querySelectorAll('p')[170];d('pdfPreviewContainer').querySelector('[data-element-id="'+block.dataset.elementId+'"]').click();const style=[...d('stylePreviewGrid').children].find(b=>b.querySelector('[data-style]')?.dataset.style==='text-lead');style.click();assert.equal(p.pages()[0],pages[0]);assert(!block.dataset.style);d('applyToSelectedBtn').click();assert.equal(p.pages()[0],pages[0]);assert.equal(block.dataset.style,'text-lead');assert.equal(d('pdfPreviewContainer').querySelectorAll('p[data-block-id]').length,200);d('undoBtn').click();assert.notEqual(d('sourceContent').querySelectorAll('p')[170].dataset.style,'text-lead');const originalPage=p.pages()[0];await p.input('fontSize','12');assert.notEqual(p.pages()[0],originalPage);assert.equal(d('pdfPreviewContainer').querySelectorAll('p[data-block-id]').length,200);p.dom.window.close();console.log('PASS: PDF unchanged pages retained during selected style preview/apply, content completeness, undo, and global-setting full reflow.');
})().catch(e=>{console.error(e);process.exitCode=1});
